name: Deploy PIMS Web App

on:
  push:
    branches:
      - staging
      - master

jobs:
  deploy_production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect with VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p apps/pims-web-app && cd apps/pims-web-app
            
            if [ -d ".git" ]; then
              git stash
              git pull origin master
            else
              git clone -b master https://github.com/yonathanth/pims-cloud-front.git .
            fi
          
            npm install --force
            npm run build

            pid=$(pm2 pid "pims-web-app" 2>/dev/null)
            if [ -n "$pid" ]; then
              echo "Reloading pims-web-app"
              pm2 reload "pims-web-app"
              pm2 save
            else
              echo "New application"
              pm2 start npm --name "pims-web-app" -- start
              pm2 startup
              pm2 save
            fi
